name: Update Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 실행 (원하는 실행 주기로 변경 가능)
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://velog.io/rss/tmdduf785"  # 본인 Velog RSS 주소 입력
